------------------------------------------------------------TBL_GENERO-------------------------------------------------------------
INSERT INTO TBL_GENERO (ID_GENERO, NOMBRE, DESCRIPCION_GENERO) VALUES (1, 'Rock', 'Género musical que se desarrolló durante y después de la década de 1950');
INSERT INTO TBL_GENERO (ID_GENERO, NOMBRE, DESCRIPCION_GENERO) VALUES (2, 'Grindcore', 'Subgénero del metal extremo que se caracteriza por su velocidad y agresividad');
INSERT INTO TBL_GENERO (ID_GENERO, NOMBRE, DESCRIPCION_GENERO) VALUES (3, 'Powerviolence', 'Estilo musical que fusiona elementos del hardcore punk con la velocidad del grindcore');
INSERT INTO TBL_GENERO (ID_GENERO, NOMBRE, DESCRIPCION_GENERO) VALUES (4, 'Power Metal', 'Subgénero del heavy metal con énfasis en la melodía y el virtuosismo instrumental');
INSERT INTO TBL_GENERO (ID_GENERO, NOMBRE, DESCRIPCION_GENERO) VALUES (5, 'Deathcore', 'Fusión de death metal y metalcore, con elementos agresivos y breakdowns potentes');
INSERT INTO TBL_GENERO (ID_GENERO, NOMBRE, DESCRIPCION_GENERO) VALUES (6, 'Stoner Rock', 'Género que incorpora elementos del rock psicodélico y el doom metal');
INSERT INTO TBL_GENERO (ID_GENERO, NOMBRE, DESCRIPCION_GENERO) VALUES (7, 'Death Metal', 'Estilo de metal extremo con letras oscuras y vocalización gutural');
INSERT INTO TBL_GENERO (ID_GENERO, NOMBRE, DESCRIPCION_GENERO) VALUES (8, 'Alt Rock', 'Abreviatura de rock alternativo, caracterizado por su diversidad estilística');
INSERT INTO TBL_GENERO (ID_GENERO, NOMBRE, DESCRIPCION_GENERO) VALUES (9, 'Hard Rock', 'Estilo de rock que se caracteriza por su ritmo potente y riffs de guitarra distintivos');
INSERT INTO TBL_GENERO (ID_GENERO, NOMBRE, DESCRIPCION_GENERO) VALUES (10, 'Thrash Metal', 'Subgénero del metal caracterizado por su rapidez y agresividad');
INSERT INTO TBL_GENERO (ID_GENERO, NOMBRE, DESCRIPCION_GENERO) VALUES (11, 'Heavy Metal', 'Estilo de metal que destaca por su uso de guitarras potentes y voces melódicas');
INSERT INTO TBL_GENERO (ID_GENERO, NOMBRE, DESCRIPCION_GENERO) VALUES (12, 'Russian Turbo Polka Metal', 'Género humorístico que combina elementos de la música rusa, polka y metal');
INSERT INTO TBL_GENERO (ID_GENERO, NOMBRE, DESCRIPCION_GENERO) VALUES (13, 'Black Doom', 'Fusión de black metal y doom metal, con atmósferas oscuras y melancólicas');
INSERT INTO TBL_GENERO (ID_GENERO, NOMBRE, DESCRIPCION_GENERO) VALUES (14, 'Groove Metal', 'Estilo que incorpora ritmos sincopados y elementos del funk en el metal');
INSERT INTO TBL_GENERO (ID_GENERO, NOMBRE, DESCRIPCION_GENERO) VALUES (15, 'Noise Rock', 'Subgénero experimental del rock que incorpora elementos de ruido y disonancia');
INSERT INTO TBL_GENERO (ID_GENERO, NOMBRE, DESCRIPCION_GENERO) VALUES (16, 'Metalcore', 'Fusión de metal y hardcore punk, con riffs de guitarra pesados y breakdowns');
INSERT INTO TBL_GENERO (ID_GENERO, NOMBRE, DESCRIPCION_GENERO) VALUES (17, 'Post Metal', 'Subgénero del metal que incorpora elementos del post rock y el shoegaze');
INSERT INTO TBL_GENERO (ID_GENERO, NOMBRE, DESCRIPCION_GENERO) VALUES (18, 'Post Hardcore', 'Subgénero del hardcore punk que incorpora elementos del post rock');
INSERT INTO TBL_GENERO (ID_GENERO, NOMBRE, DESCRIPCION_GENERO) VALUES (19, 'Post Rock', 'Estilo de rock que incorpora elementos del rock progresivo y la música clásica');
INSERT INTO TBL_GENERO (ID_GENERO, NOMBRE, DESCRIPCION_GENERO) VALUES (20, 'Progressive Metal', 'Estilo de metal que incorpora elementos del rock progresivo y el jazz');
INSERT INTO TBL_GENERO (ID_GENERO, NOMBRE, DESCRIPCION_GENERO) VALUES (21, 'Progressive Rock', 'Estilo de rock que incorpora elementos del rock psicodélico y el jazz');
INSERT INTO TBL_GENERO (ID_GENERO, NOMBRE, DESCRIPCION_GENERO) VALUES (22, 'Punk Rock', 'Estilo de rock que se caracteriza por su actitud rebelde y su simplicidad');
INSERT INTO TBL_GENERO (ID_GENERO, NOMBRE, DESCRIPCION_GENERO) VALUES (23, 'Rock Psicodélico', 'Estilo de rock que incorpora elementos de la música psicodélica');
INSERT INTO TBL_GENERO (ID_GENERO, NOMBRE, DESCRIPCION_GENERO) VALUES (24, 'Rock Sinfónico', 'Estilo de rock que incorpora elementos de la música clásica y el rock progresivo');
INSERT INTO TBL_GENERO (ID_GENERO, NOMBRE, DESCRIPCION_GENERO) VALUES (25, 'Sludge Metal', 'Subgénero del metal que incorpora elementos del doom metal y el hardcore punk');
INSERT INTO TBL_GENERO (ID_GENERO, NOMBRE, DESCRIPCION_GENERO) VALUES (26, 'Speed Metal', 'Subgénero del metal caracterizado por su rapidez y agresividad');


------------------------------------------------------------TBL_CANCIONES-------------------------------------------------------------
-- Ejecutar el script de insert_info.py


------------------------------------------------------------TBL_PERSONAS-------------------------------------------------------------
INSERt INTO TBL_PERSONAS (ID_PERSONA, NUMERO_ID, NOMBRE, APELLIDO, FECHA_DE_NACIMIENTO, CORREO, TELEFONO) VALUES (1,'0801-2000-00000','JOSE','MURILLO',to_date('15-MAY-00','DD-MON-RR'),'josem@gmail.com',99999998);
INSERt INTO TBL_PERSONAS (ID_PERSONA, NUMERO_ID, NOMBRE, APELLIDO, FECHA_DE_NACIMIENTO, CORREO, TELEFONO) VALUES (2,'0712-1999-00000','LUCAS','CHINCHILLA',to_date('01-JAN-99','DD-MON-RR'),'carlosc@gmail.com',99999997);
INSERt INTO TBL_PERSONAS (ID_PERSONA, NUMERO_ID, NOMBRE, APELLIDO, FECHA_DE_NACIMIENTO, CORREO, TELEFONO) VALUES (3,'0801-1998-00001','ROBERT','LEWANDOWSKY',to_date('25-APR-98','DD-MON-RR'),'robertl@gmail.com',32353420);
INSERt INTO TBL_PERSONAS (ID_PERSONA, NUMERO_ID, NOMBRE, APELLIDO, FECHA_DE_NACIMIENTO, CORREO, TELEFONO) VALUES (4,'0712-2001-12345','LEONEL','MESSI',to_date('08-OCT-01','DD-MON-RR'),'leom@gmail.com',33394671);
INSERt INTO TBL_PERSONAS (ID_PERSONA, NUMERO_ID, NOMBRE, APELLIDO, FECHA_DE_NACIMIENTO, CORREO, TELEFONO) VALUES (5,'0801-1997-00054','ALEXIA','PUTELLAS',to_date('08-MAR-97','DD-MON-RR'),'alexiap@gmail.com',89852413);
INSERt INTO TBL_PERSONAS (ID_PERSONA, NUMERO_ID, NOMBRE, APELLIDO, FECHA_DE_NACIMIENTO, CORREO, TELEFONO) VALUES (6,'0712-1994-00021','CARLO','COSTLY',to_date('11-DEC-94','DD-MON-RR'),'carloc@gmail.com',89545562);
INSERt INTO TBL_PERSONAS (ID_PERSONA, NUMERO_ID, NOMBRE, APELLIDO, FECHA_DE_NACIMIENTO, CORREO, TELEFONO) VALUES (7,'0801-1999-00325','MARIA','BECERRA',to_date('05-JUL-99','DD-MON-RR'),'mariab@gmail.com',97586631);
INSERt INTO TBL_PERSONAS (ID_PERSONA, NUMERO_ID, NOMBRE, APELLIDO, FECHA_DE_NACIMIENTO, CORREO, TELEFONO) VALUES (8,'0712-1991-12396','HEBER','CARDENAS',to_date('07-JUN-91','DD-MON-RR'),'heberc@gmail.com',89575369);
INSERt INTO TBL_PERSONAS (ID_PERSONA, NUMERO_ID, NOMBRE, APELLIDO, FECHA_DE_NACIMIENTO, CORREO, TELEFONO) VALUES (9,'0801-1989-00056','MARIO','CASAS',to_date('07-AUG-89','DD-MON-RR'),'marioc@gmail.com',87693415);
INSERt INTO TBL_PERSONAS (ID_PERSONA, NUMERO_ID, NOMBRE, APELLIDO, FECHA_DE_NACIMIENTO, CORREO, TELEFONO) VALUES (10,'0712-1987-00012','LUKA','MODRIC',to_date('01-FEB-87','DD-MON-RR'),'lmodric@gmail.com',89895512);


------------------------------------------------------------TBL_USUARIOS-------------------------------------------------------------
INSERt INTO TBL_USUARIOS (ID_USUARIO, ID_TIPO_USUARIO, ID_MEMBRESIA, ID_OYENTE, ID_DIRECCION, NOMBRE_USUARIO, FECHA_REGISTRO, CLAVE) 
VALUES (1, 1, 1, 1, 1, 'danielbanariba', to_date('19-03-98','DD-MM-RR'), '1234');


--------------------------------------------------------TBL_TIPO_MEMBRESIA-----------------------------------------------------------------
INSERT INTO "C##SOUNDCLOUD"."TBL_TIPO_MEMBRESIAS" (ID_TIPO_MEMBRESIA, NOMBRE_MEMBRESIA) VALUES ('1', 'SOUNDCLOUD GO')
INSERT INTO "C##SOUNDCLOUD"."TBL_TIPO_MEMBRESIAS" (ID_TIPO_MEMBRESIA, NOMBRE_MEMBRESIA) VALUES ('2', 'SOUNDCLOUD GO +')
INSERT INTO "C##SOUNDCLOUD"."TBL_TIPO_MEMBRESIAS" (ID_TIPO_MEMBRESIA, NOMBRE_MEMBRESIA) VALUES ('3', 'SOUNDCLOUD DJ')


--------------------------------------------------------TBL_MEMBRESIA-----------------------------------------------------------------
INSERT INTO "C##SOUNDCLOUD"."TBL_MEMBRESIAS" (ID_MEMBRESIA, ID_TIPO_MEMBRESIA, FECHA_INICIO, FECHA_VENCIMIENTO) VALUES ('1', '1', TO_DATE('2020-05-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2021-05-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
INSERT INTO "C##SOUNDCLOUD"."TBL_MEMBRESIAS" (ID_MEMBRESIA, ID_TIPO_MEMBRESIA, FECHA_INICIO, FECHA_VENCIMIENTO) VALUES ('2', '2', TO_DATE('2023-07-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-07-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
INSERT INTO "C##SOUNDCLOUD"."TBL_MEMBRESIAS" (ID_MEMBRESIA, ID_TIPO_MEMBRESIA, FECHA_INICIO, FECHA_VENCIMIENTO) VALUES ('3', '3', TO_DATE('2023-12-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-12-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
INSERT INTO "C##SOUNDCLOUD"."TBL_MEMBRESIAS" (ID_MEMBRESIA, ID_TIPO_MEMBRESIA, FECHA_INICIO, FECHA_VENCIMIENTO) VALUES ('4', '1', TO_DATE('2023-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
INSERT INTO "C##SOUNDCLOUD"."TBL_MEMBRESIAS" (ID_MEMBRESIA, ID_TIPO_MEMBRESIA, FECHA_INICIO, FECHA_VENCIMIENTO) VALUES ('5', '2', TO_DATE('2023-03-08 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-03-08 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
INSERT INTO "C##SOUNDCLOUD"."TBL_MEMBRESIAS" (ID_MEMBRESIA, ID_TIPO_MEMBRESIA, FECHA_INICIO, FECHA_VENCIMIENTO) VALUES ('6', '3', TO_DATE('2023-04-12 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-04-12 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
INSERT INTO "C##SOUNDCLOUD"."TBL_MEMBRESIAS" (ID_MEMBRESIA, ID_TIPO_MEMBRESIA, FECHA_INICIO, FECHA_VENCIMIENTO) VALUES ('7', '1', TO_DATE('2023-05-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-05-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
INSERT INTO "C##SOUNDCLOUD"."TBL_MEMBRESIAS" (ID_MEMBRESIA, ID_TIPO_MEMBRESIA, FECHA_INICIO, FECHA_VENCIMIENTO) VALUES ('8', '2', TO_DATE('2023-02-09 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-02-09 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
INSERT INTO "C##SOUNDCLOUD"."TBL_MEMBRESIAS" (ID_MEMBRESIA, ID_TIPO_MEMBRESIA, FECHA_INICIO, FECHA_VENCIMIENTO) VALUES ('9', '3', TO_DATE('2023-10-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-10-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
INSERT INTO "C##SOUNDCLOUD"."TBL_MEMBRESIAS" (ID_MEMBRESIA, ID_TIPO_MEMBRESIA, FECHA_INICIO, FECHA_VENCIMIENTO) VALUES ('10', '3', TO_DATE('2023-09-08 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-09-08 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))



------------------------------------------------------------TBL_PAISES--------------------------------------------------------------------
INSERT INTO "C##SOUNDCLOUD"."TBL_PAISES" (ID_PAIS, NOMBRE_PAIS) VALUES ('1', 'HONDURAS')
INSERT INTO "C##SOUNDCLOUD"."TBL_PAISES" (ID_PAIS, NOMBRE_PAIS) VALUES ('2', 'JAPON')
INSERT INTO "C##SOUNDCLOUD"."TBL_PAISES" (ID_PAIS, NOMBRE_PAIS) VALUES ('3', 'MEXICO')
INSERT INTO "C##SOUNDCLOUD"."TBL_PAISES" (ID_PAIS, NOMBRE_PAIS) VALUES ('4', 'ESTADOS UNIDOS')
INSERT INTO "C##SOUNDCLOUD"."TBL_PAISES" (ID_PAIS, NOMBRE_PAIS) VALUES ('5', 'ESPAÑA')


------------------------------------------------------------TBL_DEPARTAMENTOS-------------------------------------------------------------
INSERT INTO "C##SOUNDCLOUD"."TBL_DEPARTAMENTOS" (ID_DEPARTAMENTO, ID_PAIS, NOMBRE_DEPARTAMENTO) VALUES ('1', '1', 'FRANCISCO MORAZAN')
INSERT INTO "C##SOUNDCLOUD"."TBL_DEPARTAMENTOS" (ID_DEPARTAMENTO, ID_PAIS, NOMBRE_DEPARTAMENTO) VALUES ('2', '1', 'CORTES')
INSERT INTO "C##SOUNDCLOUD"."TBL_DEPARTAMENTOS" (ID_DEPARTAMENTO, ID_PAIS, NOMBRE_DEPARTAMENTO) VALUES ('3', '2', 'TOKYO')
INSERT INTO "C##SOUNDCLOUD"."TBL_DEPARTAMENTOS" (ID_DEPARTAMENTO, ID_PAIS, NOMBRE_DEPARTAMENTO) VALUES ('4', '2', 'OSAKA')
INSERT INTO "C##SOUNDCLOUD"."TBL_DEPARTAMENTOS" (ID_DEPARTAMENTO, ID_PAIS, NOMBRE_DEPARTAMENTO) VALUES ('5', '3', 'DISTRITO FEDERAL')
INSERT INTO "C##SOUNDCLOUD"."TBL_DEPARTAMENTOS" (ID_DEPARTAMENTO, ID_PAIS, NOMBRE_DEPARTAMENTO) VALUES ('6', '3', 'TIJUANA')
INSERT INTO "C##SOUNDCLOUD"."TBL_DEPARTAMENTOS" (ID_DEPARTAMENTO, ID_PAIS, NOMBRE_DEPARTAMENTO) VALUES ('7', '4', 'NUEVA YORK')
INSERT INTO "C##SOUNDCLOUD"."TBL_DEPARTAMENTOS" (ID_DEPARTAMENTO, ID_PAIS, NOMBRE_DEPARTAMENTO) VALUES ('8', '4', 'CHICAGO')
INSERT INTO "C##SOUNDCLOUD"."TBL_DEPARTAMENTOS" (ID_DEPARTAMENTO, ID_PAIS, NOMBRE_DEPARTAMENTO) VALUES ('9', '5', 'MADRID')
INSERT INTO "C##SOUNDCLOUD"."TBL_DEPARTAMENTOS" (ID_DEPARTAMENTO, ID_PAIS, NOMBRE_DEPARTAMENTO) VALUES ('10', '5', 'BARCELONA')

------------------------------------------------------------TBL_CIUDADES------------------------------------------------------------------
INSERT INTO "C##SOUNDCLOUD"."TBL_CIUDADES" (ID_CIUDAD, ID_DEPARTAMENTO, NOMBRE_CIUDAD) VALUES ('1', '1', 'TEGUCIGALPA')
INSERT INTO "C##SOUNDCLOUD"."TBL_CIUDADES" (ID_CIUDAD, ID_DEPARTAMENTO, NOMBRE_CIUDAD) VALUES ('2', '1', 'COMAYAGUELA')
INSERT INTO "C##SOUNDCLOUD"."TBL_CIUDADES" (ID_CIUDAD, ID_DEPARTAMENTO, NOMBRE_CIUDAD) VALUES ('3', '1', 'TALANGA')
INSERT INTO "C##SOUNDCLOUD"."TBL_CIUDADES" (ID_CIUDAD, ID_DEPARTAMENTO, NOMBRE_CIUDAD) VALUES ('4', '2', 'SAN PEDRO SULA')
INSERT INTO "C##SOUNDCLOUD"."TBL_CIUDADES" (ID_CIUDAD, ID_DEPARTAMENTO, NOMBRE_CIUDAD) VALUES ('5', '2', 'VALLE DE SULA')
INSERT INTO "C##SOUNDCLOUD"."TBL_CIUDADES" (ID_CIUDAD, ID_DEPARTAMENTO, NOMBRE_CIUDAD) VALUES ('6', '2', 'CHOLOMA')
INSERT INTO "C##SOUNDCLOUD"."TBL_CIUDADES" (ID_CIUDAD, ID_DEPARTAMENTO, NOMBRE_CIUDAD) VALUES ('7', '3', 'CHIYODA')
INSERT INTO "C##SOUNDCLOUD"."TBL_CIUDADES" (ID_CIUDAD, ID_DEPARTAMENTO, NOMBRE_CIUDAD) VALUES ('8', '3', 'MINATO')
INSERT INTO "C##SOUNDCLOUD"."TBL_CIUDADES" (ID_CIUDAD, ID_DEPARTAMENTO, NOMBRE_CIUDAD) VALUES ('9', '3', 'SHINJUKO')
INSERT INTO "C##SOUNDCLOUD"."TBL_CIUDADES" (ID_CIUDAD, ID_DEPARTAMENTO, NOMBRE_CIUDAD) VALUES ('10', '4', 'HANNAN')
INSERT INTO "C##SOUNDCLOUD"."TBL_CIUDADES" (ID_CIUDAD, ID_DEPARTAMENTO, NOMBRE_CIUDAD) VALUES ('11', '4', 'SUITA')
INSERT INTO "C##SOUNDCLOUD"."TBL_CIUDADES" (ID_CIUDAD, ID_DEPARTAMENTO, NOMBRE_CIUDAD) VALUES ('12', '4', 'YAO')
INSERT INTO "C##SOUNDCLOUD"."TBL_CIUDADES" (ID_CIUDAD, ID_DEPARTAMENTO, NOMBRE_CIUDAD) VALUES ('13', '5', 'MILPA ALTA')
INSERT INTO "C##SOUNDCLOUD"."TBL_CIUDADES" (ID_CIUDAD, ID_DEPARTAMENTO, NOMBRE_CIUDAD) VALUES ('14', '5', 'TLAHUAC')
INSERT INTO "C##SOUNDCLOUD"."TBL_CIUDADES" (ID_CIUDAD, ID_DEPARTAMENTO, NOMBRE_CIUDAD) VALUES ('15', '5', 'COYOACAN')
INSERT INTO "C##SOUNDCLOUD"."TBL_CIUDADES" (ID_CIUDAD, ID_DEPARTAMENTO, NOMBRE_CIUDAD) VALUES ('16', '6', 'CENTRO')
INSERT INTO "C##SOUNDCLOUD"."TBL_CIUDADES" (ID_CIUDAD, ID_DEPARTAMENTO, NOMBRE_CIUDAD) VALUES ('17', '6', 'LA MESA')
INSERT INTO "C##SOUNDCLOUD"."TBL_CIUDADES" (ID_CIUDAD, ID_DEPARTAMENTO, NOMBRE_CIUDAD) VALUES ('18', '6', 'PRESA ESTE')
INSERT INTO "C##SOUNDCLOUD"."TBL_CIUDADES" (ID_CIUDAD, ID_DEPARTAMENTO, NOMBRE_CIUDAD) VALUES ('19', '8', 'JOLIET')
INSERT INTO "C##SOUNDCLOUD"."TBL_CIUDADES" (ID_CIUDAD, ID_DEPARTAMENTO, NOMBRE_CIUDAD) VALUES ('20', '8', 'NAPERVILLE')
INSERT INTO "C##SOUNDCLOUD"."TBL_CIUDADES" (ID_CIUDAD, ID_DEPARTAMENTO, NOMBRE_CIUDAD) VALUES ('21', '8', 'CHICAGO')
INSERT INTO "C##SOUNDCLOUD"."TBL_CIUDADES" (ID_CIUDAD, ID_DEPARTAMENTO, NOMBRE_CIUDAD) VALUES ('22', '7', 'ALBANY')
INSERT INTO "C##SOUNDCLOUD"."TBL_CIUDADES" (ID_CIUDAD, ID_DEPARTAMENTO, NOMBRE_CIUDAD) VALUES ('23', '7', 'BRONX')
INSERT INTO "C##SOUNDCLOUD"."TBL_CIUDADES" (ID_CIUDAD, ID_DEPARTAMENTO, NOMBRE_CIUDAD) VALUES ('24', '7', 'MONROE')
INSERT INTO "C##SOUNDCLOUD"."TBL_CIUDADES" (ID_CIUDAD, ID_DEPARTAMENTO, NOMBRE_CIUDAD) VALUES ('25', '9', 'SALAMANCA')
INSERT INTO "C##SOUNDCLOUD"."TBL_CIUDADES" (ID_CIUDAD, ID_DEPARTAMENTO, NOMBRE_CIUDAD) VALUES ('26', '9', 'CHUECA')
INSERT INTO "C##SOUNDCLOUD"."TBL_CIUDADES" (ID_CIUDAD, ID_DEPARTAMENTO, NOMBRE_CIUDAD) VALUES ('27', '9', 'MALASAÑA')
INSERT INTO "C##SOUNDCLOUD"."TBL_CIUDADES" (ID_CIUDAD, ID_DEPARTAMENTO, NOMBRE_CIUDAD) VALUES ('28', '10', 'GRACIA')
INSERT INTO "C##SOUNDCLOUD"."TBL_CIUDADES" (ID_CIUDAD, ID_DEPARTAMENTO, NOMBRE_CIUDAD) VALUES ('29', '10', 'NOU BARRIS')
INSERT INTO "C##SOUNDCLOUD"."TBL_CIUDADES" (ID_CIUDAD, ID_DEPARTAMENTO, NOMBRE_CIUDAD) VALUES ('30', '10', 'CATALUÑA')


------------------------------------------------------------TBL_DIRECIONES--------------------------------------------------------------------
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('1', '1', 'AV 4, CALLE 7, CASA 1')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('2', '1', 'AV 4, CALLE 1, CASA 78')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('3', '2', 'AV 4, CALLE 7, CASA 11')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('4', '2', 'AV 4, CALLE 1, CASA 73')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('5', '3', 'AV 4, CALLE 7, CASA 14')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('6', '3', 'AV 4, CALLE 1, CASA 77')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('7', '4', 'AV 4, CALLE 7, CASA 2')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('8', '4', 'AV 4, CALLE 1, CASA 8')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('9', '5', 'AV 4, CALLE 7, CASA 5')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('10', '5', 'AV 4, CALLE 1, CASA 78')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('11', '6', 'AV 4, CALLE 7, CASA 15')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('12', '6', 'AV 4, CALLE 1, CASA 45')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('13', '7', 'AV 4, CALLE 7, CASA 54')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('14', '7', 'AV 4, CALLE 1, CASA 61')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('15', '8', 'AV 4, CALLE 7, CASA 45')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('16', '8', 'AV 4, CALLE 2, CASA 7')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('17', '9', 'AV 4, CALLE 7, CASA 41')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('18', '9', 'AV 4, CALLE 5, CASA 7')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('19', '10', 'AV 4, CALLE 4, CASA 3')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('20', '10', 'AV 4, CALLE 6, CASA 8')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('21', '11', 'AV 4, CALLE 4, CASA 13')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('22', '11', 'AV 4, CALLE 45, CASA 8')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('23', '12', 'AV 4, CALLE S, CASA 4')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('24', '12', 'AV 4, CALLE H, CASA 48')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('25', '13', 'AV 4, CALLE F, CASA 61')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('26', '13', 'AV 4, CALLE G, CASA 73')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('27', '14', 'AV 4, CALLE T, CASA 10')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('28', '14', 'AV 4, CALLE S, CASA 70')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('29', '15', 'AV 4, CALLE S, CASA 16')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('30', '15', 'AV 4, CALLE Y, CASA 13')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('31', '16', 'AV 3, CALLE 1, CASA 78')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('32', '17', 'AV 44, CALLE 7 CASA 11')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('33', '17', 'AV 5, CALLE 1, CASA 73')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('34', '18', 'AV 6, CALLE 7 CASA 14')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('35', '18', 'AV 23, CALLE 1, CASA 77')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('36', '19', 'AV 1, CALLE 7 CASA 2')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('37', '19', 'AV 2,CALLE 1, CASA 8')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('38', '20', 'AV 3, CALLE 7 CASA 5')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('39', '20', 'AV 4,CALLE 1, CASA 78')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('40', '21', 'AV 5, CALLE 7 CASA 15')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('41', '21', 'AV 6,CALLE 1, CASA 45')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('42', '22', 'AV 7, CALLE 7 CASA 54')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('43', '22', 'AV 8,CALLE 1, CASA 61')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('44', '23', 'AV 9, CALLE 7 CASA 45')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('45', '23', 'AV 9,CALLE 2, CASA 7')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('46', '24', 'AV 8, CALLE 7 CASA 41')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('47', '24', 'AV 7,CALLE 5, CASA 7')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('48', '25', 'AV 6, CALLE 4 CASA 3')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('49', '25', 'AV 5,CALLE 6, CASA 8')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('50', '26', 'AV 4, CALLE 4 CASA 13')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('51', '26', 'AV 3,CALLE 45, CASA 8')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('52', '27', 'AV 2, CALLE S CASA 4')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('53', '27', 'AV 1,CALLE H, CASA 48')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('54', '28', 'AV 0, CALLE F CASA 61')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('55', '28', 'AV 0,CALLE G, CASA 73')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('56', '29', 'AV 1, CALLE T CASA 10')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('57', '29', 'AV 2,CALLE S, CASA 70')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('58', '30', 'AV 3, CALLE S CASA 16')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('59', '30', 'AV 4,CALLE Y, CASA 13')
INSERT INTO "C##SOUNDCLOUD"."TBL_DIRECCION" (ID_DIRECCION, ID_CIUDAD, DESCRIPCION) VALUES ('60', '16', 'AV 2, CALLE 7 CASA 1')


------------------------------------------------------------TBL_USUARIOS------------------------------------------------------------------